import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.util.Collections;
import java.util.Date;
//import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.zip.GZIPInputStream;



public class MultiVCFAnalyzer {

	/**
	 * @param args
	 */
	public static void main(String[] args) throws Exception
	{
		String programName = "MultiVCFAnalyzer";
		String author = "Alexander Herbig";
		String authorsEmail = "alexander_herbig@eva.mpg.de";
		String version = "0.89";
		
		System.out.println(programName+" - "+version+"\nby "+author+"\n");
		
		String helpString = "Please start the program with the following parameters in exactly this order:\n\nSNP effect analysis result file (from SnpEff; txt format)\nReference genome fasta file\nReference genome gene annotation (gff)\nOutput directory\nWrite allele frequencies ('T' or 'F')\nMinimal genotyping quality (GATK)\nMinimal coverage for base call\nMinimal allele frequency for homozygous call\nMinimal allele frequency for heterozygous call\nList of positions to exclude (gff)\n[vcf_files ...] input vcf files as generated by the GATK UnifiedGenotyper\n\nTo omit an optional input file put NA as the file name.\nThe SnpEff file, the reference gene annotation, and excluded positions are optional.";
		
		if(args.length==0 || args[0].equalsIgnoreCase("--help") || args[0].equalsIgnoreCase("-help") || args[0].equalsIgnoreCase("-?") || args[0].equalsIgnoreCase("-h"))
		{
			System.out.println("--- How to use "+programName+" ---\n");
			System.out.println(helpString);
			System.out.println("\nIn case of any questions contact "+author+" ("+authorsEmail+").");
			return;
		}
		
		String snpEffOutputFile = args[0];
		
		String refFastaFile = args[1]; //
		
		String refGFF = args[2];
		
		String outputFolder = args[3];
		
		String outSNPfasta = outputFolder+"/snpAlignment.fasta";
		String outSNPfastaWithRef = outputFolder+"/snpAlignmentIncludingRefGenome.fasta";
		String outFullAlignmentFasta = outputFolder+"/fullAlignment.fasta";
		String outStatTable = outputFolder+"/snpStatistics.tsv";
		String outSNPtable = outputFolder+"/snpTable.tsv";
		String outSNPtableWithUncertaintyCalls = outputFolder+"/snpTableWithUncertaintyCalls.tsv";
		String outSNPtable4SnpEff = outputFolder+"/snpTableForSnpEff.tsv";
		String outSNPtableWithSnpEffInfos = outputFolder+"/snpTableWithSnpEffInfos.tsv";
		String outSNPtableWithUncertaintyCallsWithSnpEffInfos = outputFolder+"/snpTableWithUncertaintyCallsWithSnpEffInfos.tsv";
		String outGenoTypeTable4Structure = outputFolder+"/structureGenotypes.tsv";
		String outGenoTypeTable4StructureCompDel = outputFolder+"/structureGenotypes_noMissingData-Columns.tsv";
		String outGenoTypeMatrix = outputFolder+"/genotypeMatrix.tsv";
		String outGenoTypeFreqMatrix = outputFolder+"/genotypeFreqMatrix.tsv";
		String outJSON = outputFolder+"/MultiVCFAnalyzer.json";
		
		String infoOut = outputFolder+"/info.txt";
		
		boolean writeFreqsInStatTable = parseBoolean(args[4]);
		
		double minQual = Double.parseDouble(args[5]);
		int minCov = Integer.parseInt(args[6]);
		double minHomSNPallelFreq = Double.parseDouble(args[7]);
		double minHetSNPallelFreq = Double.parseDouble(args[8]);
		
		String positions2ExcludeFiles = args[9];//Can be up to two files: 1st: repeat regs etc. 2nd: CDS file to exclude 1st,2nd codon pos
		
		Map<String,Set<Integer>> positions2ExcludeSet = getPositionsToExclude(positions2ExcludeFiles);
		
		int vcfArgumentsOffset = 10;
		
		int numVCFs = args.length-vcfArgumentsOffset;
		
		Map<String,String> refGenome = FASTAParser.parseDNA(refFastaFile); 
		
		
		int numOutgroups = 0;
		
		// make output folder
		File dataDir = new File(outputFolder);
		if(!dataDir.exists())
		{
			dataDir.mkdir();
			System.out.println("Created output directory:\n"+outputFolder);
		}
		
		//write initial infos
		BufferedWriter infobw = new BufferedWriter(new FileWriter(infoOut));
		
		infobw.write(programName+" - "+version+"\nby "+author+"\n\n");
		infobw.write("Input files:\n");
		infobw.write("Reference genome fasta file: "+refFastaFile+"\n");
		infobw.write("Reference genome gene annotation (gff): "+refGFF+"\n");
		infobw.write("List of positions to exclude (gff): "+positions2ExcludeFiles+"\n");
		infobw.write("SNP effect analysis result file (from SnpEff): "+snpEffOutputFile+"\n");
		
		infobw.write("\nOutput files:\n");
		infobw.write("Output directory: "+outputFolder+"\n");
		infobw.write("SNP alignment (fasta): "+outSNPfasta+"\n");
		infobw.write("SNP alignment including entry for reference genome (fasta): "+outSNPfastaWithRef+"\n");
		infobw.write("SNP table: "+outSNPtable+"\n");
		infobw.write("SNP table with uncertainty calls: "+outSNPtableWithUncertaintyCalls+"\n");
		if((new File(snpEffOutputFile)).exists())
		{
			infobw.write("SNP table with SnpEff infos: "+outSNPtableWithSnpEffInfos+"\n");
			infobw.write("SNP table with uncertainty calls with SnpEff infos: "+outSNPtableWithUncertaintyCallsWithSnpEffInfos+"\n");
		}
		infobw.write("SNP table to be used as input for SnpEff: "+outSNPtable4SnpEff+"\n");
		infobw.write("SNP table to be used as input for STRUCTURE: "+outGenoTypeTable4Structure+"\n");
		infobw.write("SNP table to be used as input for STRUCTURE (no columns with missing data): "+outGenoTypeTable4StructureCompDel+"\n");
		infobw.write("SNP calling statistics: "+outStatTable+"\n");
		
		infobw.write("\nParameters:\n");
		infobw.write("Minimal genotyping quality (GATK): "+minQual+"\n");
		infobw.write("Minimal coverage for base call: "+minCov+"\n");
		infobw.write("Minimal allele frequency for homozygous call: "+minHomSNPallelFreq+"\n");
		infobw.write("Minimal allele frequency for heterozygous call: "+minHetSNPallelFreq+"\n");
		infobw.write("Write allele frequencies: "+writeFreqsInStatTable+"\n");
		
		infobw.write("\nAdditional notes:\n");
		infobw.write("Number of genomes (vcf files): "+numVCFs+"\n");
		Date date = new Date();
		infobw.write("Run started: "+date.toGMTString()+"\n");
		
		//write initial infos into json
		BufferedWriter jsonbw = new BufferedWriter(new FileWriter(outJSON));
		
		jsonbw.write("{\n");
		jsonbw.write("  \"metadata\": {\n");
		jsonbw.write("    \"tool_name\": \"MultiVCFAnalyzer\",\n");
		jsonbw.write("    \"version\": \""+version+"\",\n");
		jsonbw.write("    \"numVCFs\": "+numVCFs+",\n");
		jsonbw.write("    \"quality_threshold\": "+minQual+",\n");
		jsonbw.write("    \"coverage_threshold\": "+minCov+",\n");
		jsonbw.write("    \"min_snp_allele_freq_hom\": "+minHomSNPallelFreq+",\n");
		jsonbw.write("    \"min_snp_allele_freq_het\": "+minHetSNPallelFreq+"\n");
		jsonbw.write("  },\n");

		
		//SNP array
		Map<String,char[][]> snpColumns = new LinkedHashMap<String,char[][]>();
		
		Map<String,char[][]> uncertainSnpColumns = new LinkedHashMap<String,char[][]>();
		
		Map<String,Set<Integer>> snpPositions = new LinkedHashMap<String,Set<Integer>>();
				
		Map<String,double[][]> snpFrequencies = new LinkedHashMap<String,double[][]>();
		
		char nChar='N';
		char rChar='R';
		
		//initialize arrays
		for (Map.Entry<String, String> entry : refGenome.entrySet())
		{
		    String chromName = entry.getKey();
		    String chromSeq = entry.getValue();

		    if (chromSeq != null)
		    { 
		        int chromLength = chromSeq.length();
		       
		        snpColumns.put(chromName, new char[chromLength][numVCFs]);
		        uncertainSnpColumns.put(chromName, new char[chromLength][numVCFs]);
		        snpPositions.put(chromName,new HashSet<Integer>());
		        snpFrequencies.put(chromName, new double[chromLength][numVCFs]);
		        
		        //initialize empty positions2ExcludeSets
		        if(positions2ExcludeSet.get(chromName)==null)
		        	positions2ExcludeSet.put(chromName, new HashSet<Integer>());
		        
		        //Fill SNP array
				for(int i=0; i<chromLength; i++)
					for(int j=0; j<numVCFs; j++)
					{
						snpColumns.get(chromName)[i][j] = nChar;
						uncertainSnpColumns.get(chromName)[i][j] = nChar;
					}
		    }
		    else 
		    {
		        throw(new Error("ERROR: Empty chromosome sequence: "+chromName));
		    }
		}
		
		//validate chromosome/contig names in positions2ExcludeSet
		for (Map.Entry<String, Set<Integer>> entry : positions2ExcludeSet.entrySet())
			if(!refGenome.containsKey(entry.getKey()))
				throw(new Error("Chromosome/contig ID "+entry.getKey()+" not part of reference. ID appears in: "+positions2ExcludeFiles));
		
		
		/////////////////////////
		// BEGIN -- Parse VCFs //
		/////////////////////////
		BufferedReader br;
		BufferedWriter statbw = new BufferedWriter(new FileWriter(outStatTable));
		statbw.write("SNP statistics for "+numVCFs+" samples.\nQuality Threshold: "+minQual+"\nCoverage Threshold: "+minCov+"\nMinimum SNP allele frequency: "+minHomSNPallelFreq+"\n");
		statbw.write("sample\tSNP Calls (all)\tSNP Calls (het)\tcoverage(fold)\tcoverage(percent)\trefCall\tallPos\tnoCall\tdiscardedRefCall\tdiscardedVarCall\tfilteredVarCall\tunhandledGenotype\n");
		
		//start json
		jsonbw.write("  \"metrics\": {\n");
		

		//counter
		int covCount = 0;
		int allPos = 0;
		int noCallPos = 0;
		int nonStandardRefChars = 0;
		int refCallPos = 0;
		int varCallPos = 0;
		int hetVarCallPos = 0;
		int discardedRefCall = 0;
		int discardedVarCall = 0;
		int filteredVarCall = 0;
		int unknownCall = 0;
		
		int ns;
		double nperc;
		double covround;
		
		String line;
		String[] cols;
		
		String chromName;
		
		double qual;
		int cov;
		double SNPallelFreq;
		String[] allelCols;
		
		int lastPos1based = 0;
		int currPos1based = 0;
		long startTime = System.currentTimeMillis();
		long timeLeft;
		boolean outgroup;
		for(int vcfIndex =0; vcfIndex<numVCFs; vcfIndex++)
		{
			br = new BufferedReader(new InputStreamReader(new GZIPInputStream(new FileInputStream(args[vcfIndex+vcfArgumentsOffset])))); //br = new BufferedReader(new FileReader(args[vcfIndex+vcfArgumentsOffset]));
			
			System.out.println("Now processing "+(vcfIndex+1)+"/"+numVCFs+": "+getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]));
			
			//Is this an outgroup?
			//If yes, do not consider positions that are only variant in the outgroup.
			if(getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]).startsWith("outgroup"))
			{
				System.out.println("This is an outgroup! Outgroup-specific SNPs will not be considered.");
				infobw.write(getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset])+" was labeled as an outgroup.\n");
				outgroup=true;
				numOutgroups++;
			}
			else
				outgroup=false;
			
			//counter
			covCount=0;
			allPos = 0;
			noCallPos = 0;
			nonStandardRefChars = 0;
			refCallPos = 0;
			varCallPos = 0;
			hetVarCallPos = 0;
			discardedRefCall = 0;
			discardedVarCall = 0;
			filteredVarCall = 0;
			unknownCall = 0;
			
			lastPos1based = 0;
			currPos1based = 0;
			
			while((line=br.readLine()) != null)
			{
				if(line.startsWith("#"))
				{
					continue;
				}
				
				//count
				allPos++;
				
				if(allPos%500000==0)
					System.out.println(allPos+" positions processed.");
				
				cols = line.split("\t");
				
				//insert Ns at not handled sites, which are left out by GATK
				lastPos1based=currPos1based;
				
				chromName = cols[0];
				
				//Error, if chromosome does not exist
				if (!refGenome.containsKey(chromName)) {
				    throw new Error("Chromosome/contig ID "+chromName+" not part of reference. ID appears in VCF: "+getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]));
				}
				
				currPos1based = Integer.parseInt(cols[1]);
				
				allelCols = cols[9].split(":");
				
				//No call
				if(allelCols[0].equals("./."))
				{
					noCallPos++;
				}
				//Reference Call
				else if(allelCols[0].equals("0/0"))
				{
					qual = Double.parseDouble(cols[5]);
					cov=Integer.parseInt(allelCols[1]);
					covCount+=cov;
					
					if(qual>=minQual && cov >= minCov)
					{
						refCallPos++;
						
						snpColumns.get(chromName)[currPos1based-1][vcfIndex] = refGenome.get(chromName).charAt(currPos1based-1);
						uncertainSnpColumns.get(chromName)[currPos1based-1][vcfIndex] = refGenome.get(chromName).charAt(currPos1based-1);
					}
					else
					{
						discardedRefCall++;
						uncertainSnpColumns.get(chromName)[currPos1based-1][vcfIndex] = rChar;
					}
				}
				//variant call
				else if(allelCols[0].equals("0/1") || allelCols[0].equals("1/1"))
				{
					qual = Double.parseDouble(cols[5]);
					cov=Integer.parseInt(allelCols[1].split(",")[1]);
					SNPallelFreq=Math.min((double)cov/(cov+Integer.parseInt(allelCols[1].split(",")[0])-1) , 1); // -1 because once doesn't count
					
					if(writeFreqsInStatTable)
						snpFrequencies.get(chromName)[currPos1based-1][vcfIndex] = SNPallelFreq;
					
					covCount+=cov+Integer.parseInt(allelCols[1].split(",")[0]);
					
					if(qual>=minQual && cov >= minCov && SNPallelFreq >= minHomSNPallelFreq)
					{
						if(positions2ExcludeSet.get(chromName).contains(currPos1based))
							filteredVarCall++;
						else
							varCallPos++;
						
						snpColumns.get(chromName)[currPos1based-1][vcfIndex] = cols[4].charAt(0);
						uncertainSnpColumns.get(chromName)[currPos1based-1][vcfIndex] = cols[4].charAt(0);
						
						if(!outgroup)
							snpPositions.get(chromName).add(currPos1based);
						
					}
					else if(qual>=minQual && cov >= minCov && SNPallelFreq >= minHetSNPallelFreq)
					{
						if(positions2ExcludeSet.get(chromName).contains(currPos1based))
							filteredVarCall++;
						else
						{
							varCallPos++;
							hetVarCallPos++;
						}
						
						snpColumns.get(chromName)[currPos1based-1][vcfIndex] = getAmbiguousBase(refGenome.get(chromName).charAt(currPos1based-1) , cols[4].charAt(0));
						uncertainSnpColumns.get(chromName)[currPos1based-1][vcfIndex] = getAmbiguousBase(refGenome.get(chromName).charAt(currPos1based-1) , cols[4].charAt(0));

						if(!outgroup)
							snpPositions.get(chromName).add(currPos1based);
						
					}
					else
					{
						cov=Integer.parseInt(allelCols[1].split(",")[0]);
						
						SNPallelFreq=(double)cov/(cov+Integer.parseInt(allelCols[1].split(",")[1])-1); // -1 because once doesn't count
						
						if(qual>=minQual && cov >= minCov)
						{
							if(SNPallelFreq>=minHomSNPallelFreq)
							{
								refCallPos++;
								
								snpColumns.get(chromName)[currPos1based-1][vcfIndex] = refGenome.get(chromName).charAt(currPos1based-1);
								uncertainSnpColumns.get(chromName)[currPos1based-1][vcfIndex] = refGenome.get(chromName).charAt(currPos1based-1);
							}
							else
							{
								//System.err.println("DEBUG: "+getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset])+" pos: "+currPos1based);
								discardedVarCall++;
							}
						}
						else
						{
							discardedVarCall++;
														
							if(allelCols[0].equals("1/1"))
								uncertainSnpColumns.get(chromName)[currPos1based-1][vcfIndex] = Character.toLowerCase(cols[4].charAt(0));							
						}
					}
					
				}
				//unhandled genotype
				else
				{
					unknownCall++;
					//System.err.println("WARNING: The Genotype "+allelCols[0]+" cannot be handled:\n"+line+"\nInserting 'N'!");
				}
				
			}
			br.close();
			
			//write stats
			ns = discardedRefCall+discardedVarCall+noCallPos+unknownCall+nonStandardRefChars;
			nperc = Math.round(((ns*100d)/allPos)*100)/100d;
			covround = Math.round((covCount/(double)allPos)*100)/100d;

			statbw.write(getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset])+"\t"+varCallPos+"\t"+hetVarCallPos+"\t"+covround+"\t"+(100-nperc)+"\t"+refCallPos+"\t"+allPos+"\t"+noCallPos+"\t"+discardedRefCall+"\t"+discardedVarCall+"\t"+filteredVarCall+"\t"+unknownCall+"\n");
			
			//write stats to json
			jsonbw.write("   \""+getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset])+"\": {\n");
			jsonbw.write("      \"SNP Calls (all)\": "+varCallPos+",\n");
			jsonbw.write("      \"SNP Calls (het)\": "+hetVarCallPos+",\n");
			jsonbw.write("      \"coverage (fold)\": "+covround+",\n");
			jsonbw.write("      \"coverage (percent)\": "+(100-nperc)+",\n");
			jsonbw.write("      \"refCall\": "+refCallPos+",\n");
			jsonbw.write("      \"allPos\": "+allPos+",\n");
			jsonbw.write("      \"noCall\": "+noCallPos+",\n");
			jsonbw.write("      \"discardedRefCall\": "+discardedRefCall+",\n");
			jsonbw.write("      \"discardedVarCall\": "+discardedVarCall+",\n");
			jsonbw.write("      \"filteredVarCall\": "+filteredVarCall+",\n");
			jsonbw.write("      \"unhandledGenotype\": "+unknownCall+"\n");
			jsonbw.write("    }");
			//all have a ',' but the last
			if (vcfIndex+vcfArgumentsOffset!=args.length-1)
				jsonbw.write(",");
			jsonbw.write("\n");
			
			//Time
			timeLeft =Math.round(((System.currentTimeMillis()-startTime)/(double)(vcfIndex+1))*(numVCFs-(vcfIndex+1)));
			System.out.println("\t("+Math.round(timeLeft/60000)+" minutes remaining)");
		}
		statbw.close();
		
		//finalize json
		jsonbw.write("  }\n");
		jsonbw.write("}\n");
		jsonbw.close();
		
		//////////////////////
		//END -- Parse VCFs //
		//////////////////////
		
		// Check if SNP positions are really SNPs
		
		// Exclude Positions (like repeat regions)
		
		excludePositionsFromSet(snpPositions, positions2ExcludeFiles);
		
		
		//create list	
		Map<String, List<Integer>> snpPositionList = new LinkedHashMap<String, List<Integer>>();

		for(Map.Entry<String, Set<Integer>> entry : snpPositions.entrySet())
		{
		    List<Integer> sortedPositions = new LinkedList<Integer>(entry.getValue());
		    Collections.sort(sortedPositions);
		    snpPositionList.put(entry.getKey(), sortedPositions);
		}
		
		//Write SNP table
		System.out.println("Writing SNP table:\n"+outSNPtable);
		
		BufferedWriter snptabbw = new BufferedWriter(new FileWriter(outSNPtable));
		
		snptabbw.write("Chrom\tPosition\tRef");
		for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
		{
			snptabbw.write("\t"+getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]));
		}
		snptabbw.newLine();
		
		char tmpchar;
		
		for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
		{
			for(int pos : entry.getValue())
			{
				snptabbw.write(entry.getKey()+"\t"+pos+"\t"+refGenome.get(entry.getKey()).charAt(pos-1));
				
				for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
				{
					snptabbw.write("\t");
					tmpchar = snpColumns.get(entry.getKey())[pos-1][vcfIndex];
					if(tmpchar==refGenome.get(entry.getKey()).charAt(pos-1))
						snptabbw.write(".");
					else
					{
						snptabbw.write(tmpchar);
						
						if(writeFreqsInStatTable && tmpchar!='N')
						{
							snptabbw.write(" ("+Math.round(snpFrequencies.get(entry.getKey())[pos-1][vcfIndex]*1000d)/10d+")");
						}
					}
				}
				snptabbw.newLine();
			}
		}
		
		snptabbw.close();
		
		//Write SNP table with uncertainty calls
		//Identical to previous code (3 differences)
		System.out.println("Writing SNP table with uncertainty calls:\n"+outSNPtableWithUncertaintyCalls); // 1/3 differences
		
		snptabbw = new BufferedWriter(new FileWriter(outSNPtableWithUncertaintyCalls)); // 2/3 differences
		
		snptabbw.write("Chrom\tPosition\tRef");
		for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
		{
			snptabbw.write("\t"+getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]));
		}
		snptabbw.newLine();
		
		for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
		{
			for(int pos : entry.getValue())
			{
				snptabbw.write(entry.getKey()+"\t"+pos+"\t"+refGenome.get(entry.getKey()).charAt(pos-1));
				
				for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
				{
					snptabbw.write("\t");
					tmpchar = uncertainSnpColumns.get(entry.getKey())[pos-1][vcfIndex]; // 3/3 differences
					if(tmpchar==refGenome.get(entry.getKey()).charAt(pos-1))
						snptabbw.write(".");
					else
					{
						snptabbw.write(tmpchar);
						
						if(writeFreqsInStatTable && tmpchar!='N')
						{
							snptabbw.write(" ("+Math.round(snpFrequencies.get(entry.getKey())[pos-1][vcfIndex]*1000d)/10d+")");
						}
					}
				}
				snptabbw.newLine();
			}
		}
		
		snptabbw.close();
		
		//Write SNP multi fasta
		BufferedWriter bw = new BufferedWriter(new FileWriter(outSNPfasta));
		
		System.out.println("Writing SNP alignment (fasta):\n"+outSNPfasta);
		
		StringBuffer tmpSeq;

		for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
		{
			tmpSeq=new StringBuffer();
			for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
				for(int pos : entry.getValue())
					tmpSeq.append(snpColumns.get(entry.getKey())[pos-1][vcfIndex]);
			
			FASTAWriter.write(bw, getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]), tmpSeq.toString());
		}
		
		
		bw.close();
		
		//Write SNP multi fasta with reference genome 
		
		bw = new BufferedWriter(new FileWriter(outSNPfastaWithRef)); 
		
		System.out.println("Writing SNP alignment including reference genome (fasta):\n"+outSNPfastaWithRef);
		
		tmpSeq=new StringBuffer();
		for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
			for(int pos : entry.getValue())
				tmpSeq.append(refGenome.get(entry.getKey()).charAt(pos-1));
		
		FASTAWriter.write(bw, "Reference", tmpSeq.toString());
		
		for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
		{
			tmpSeq=new StringBuffer();
			for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
				for(int pos : entry.getValue())
					tmpSeq.append(snpColumns.get(entry.getKey())[pos-1][vcfIndex]);
			
			FASTAWriter.write(bw, getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]), tmpSeq.toString());
		}
		
				
		bw.close();
		
		//Write FULL multi fasta with reference genome 
		
		bw = new BufferedWriter(new FileWriter(outFullAlignmentFasta)); 
		
		System.out.println("Writing full alignment including reference genome (fasta):\n"+outFullAlignmentFasta);
		
		tmpSeq=new StringBuffer();
		for(Map.Entry<String, String> entry : refGenome.entrySet())
			for(int pos=1;pos<=entry.getValue().length();pos++)
				tmpSeq.append(entry.getValue().charAt(pos-1));
		
		FASTAWriter.write(bw, "Reference", tmpSeq.toString());
		
		for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
		{
			tmpSeq=new StringBuffer();
			
			for(Map.Entry<String, String> entry : refGenome.entrySet())
				for(int pos=1;pos<=entry.getValue().length();pos++)
					tmpSeq.append(snpColumns.get(entry.getKey())[pos-1][vcfIndex]);
			
			FASTAWriter.write(bw, getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]), tmpSeq.toString());
		}
				
		bw.close();
		
		//write Genotypes for Structure
		bw = new BufferedWriter(new FileWriter(outGenoTypeTable4Structure));
		
		System.out.println("Writing genotypes for structure analysis:\n"+outGenoTypeTable4Structure);
		
		//first row for linked loci
		
		int prevpos=0;
		boolean first = true;
		for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
		{
			bw.append("-1");
			prevpos=0;
			first = true;
			for(int pos : entry.getValue())
			{
				if(first)
				{
					first=false;
					prevpos = pos;
					continue;
				}
				else
				{
					bw.append("\t"+(pos-prevpos));
					prevpos=pos;
				}
			}
		}
		
		for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
		{
			bw.newLine();
			bw.append(getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]));
			for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
				for(int pos : entry.getValue())
					bw.append("\t"+getGenotypeEncoding(snpColumns.get(entry.getKey())[pos-1][vcfIndex]));
		}
		
		bw.close();
		
		//write Genotypes for Structure (no missing data)
		bw = new BufferedWriter(new FileWriter(outGenoTypeTable4StructureCompDel));
		
		System.out.println("Writing genotypes for structure analysis (no missing data columns):\n"+outGenoTypeTable4StructureCompDel);
		
		//first row for linked loci

		prevpos = 0;
		first = true;
		for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
		{
			bw.append("-1");
			prevpos=0;
			first = true;
			for(int pos : entry.getValue())
			{
				if(!hasMissingData(snpColumns.get(entry.getKey())[pos-1],nChar))
				{
					if(first)
					{
						first=false;
						prevpos = pos;
						continue;
					}
					else
					{
						bw.append("\t"+(pos-prevpos));
						prevpos=pos;
					}
				}
			}
		}
		
		for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
		{
			bw.newLine();
			bw.append(getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]));
			for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
				for(int pos : entry.getValue())
					if(!hasMissingData(snpColumns.get(entry.getKey())[pos-1],nChar))
						bw.append("\t"+getGenotypeEncoding(snpColumns.get(entry.getKey())[pos-1][vcfIndex]));
		}
		
		bw.close();
		
		//Write Genotype Matrix
		System.out.println("Writing Genotype Matrix:\n"+outGenoTypeMatrix);
		if(!writeFreqsInStatTable)
			System.out.println("WARNING: No SNP frequencies calculated! The matrix will be imprecise! Switch on SNP frequency calculation!");
		
		snptabbw = new BufferedWriter(new FileWriter(outGenoTypeMatrix));
		
		snptabbw.write("Chrom\tPosition\tRef");
		for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
		{
			snptabbw.write("\t"+getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]));
		}
		snptabbw.newLine();
		
		for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
			for(int pos : entry.getValue())
			{
				snptabbw.write(entry.getKey()+"\t"+pos+"\t"+refGenome.get(entry.getKey()).charAt(pos-1));
				
				for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
				{
					snptabbw.write("\t");
					tmpchar = snpColumns.get(entry.getKey())[pos-1][vcfIndex];
					if(tmpchar==refGenome.get(entry.getKey()).charAt(pos-1))
						snptabbw.write("-1");
					else
					{
						if(tmpchar=='N')
							snptabbw.write('?');
						
						if(!writeFreqsInStatTable && tmpchar!='N')
						{
							snptabbw.write('1');
						}
						
						if(writeFreqsInStatTable && tmpchar!='N')
						{
							if(snpFrequencies.get(entry.getKey())[pos-1][vcfIndex]<minHomSNPallelFreq)
								snptabbw.write('0');
							else
								snptabbw.write('1');
						}
					}
				}
				snptabbw.newLine();
			}
		
		snptabbw.close();
		
		//Write Genotype Freq Matrix
		System.out.println("Writing Genotype Frequency Matrix:\n"+outGenoTypeFreqMatrix);
		if(!writeFreqsInStatTable)
			System.out.println("WARNING: No SNP frequencies calculated! The matrix will be imprecise! Switch on SNP frequency calculation!");
		
		snptabbw = new BufferedWriter(new FileWriter(outGenoTypeFreqMatrix));
		
		snptabbw.write("Chrom\tPosition\tRef");
		for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
		{
			snptabbw.write("\t"+getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]));
		}
		snptabbw.newLine();
		
		for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
			for(int pos : entry.getValue())
			{
				snptabbw.write(entry.getKey()+"\t"+pos+"\t"+refGenome.get(entry.getKey()).charAt(pos-1));
				
				for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
				{
					snptabbw.write("\t");
					tmpchar = snpColumns.get(entry.getKey())[pos-1][vcfIndex];
					if(tmpchar==refGenome.get(entry.getKey()).charAt(pos-1))
						snptabbw.write("0.0");
					else
					{
						if(tmpchar=='N')
							snptabbw.write('?');
						
						if(!writeFreqsInStatTable && tmpchar!='N')
						{
							snptabbw.write("1.0");
						}
						
						if(writeFreqsInStatTable && tmpchar!='N')
						{
							if(snpFrequencies.get(entry.getKey())[pos-1][vcfIndex]<minHomSNPallelFreq)
								snptabbw.write(Double.toString(Math.min(snpFrequencies.get(entry.getKey())[pos-1][vcfIndex], 1.0)));
							else
								snptabbw.write("1.0");
						}
					}
				}
			snptabbw.newLine();
		}
		
		snptabbw.close();

		//Write SNPeff table
		bw = new BufferedWriter(new FileWriter(outSNPtable4SnpEff));
		
		Set<Character> validChars = new HashSet<Character>();
		validChars.add('A'); validChars.add('C'); validChars.add('G'); validChars.add('T');
		
		Set<Character> toChars = new HashSet<Character>();
		char[] columnChars;
		
		first=true;
		
		for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
			for(int pos : entry.getValue())
			{
				toChars.clear();
				columnChars = snpColumns.get(entry.getKey())[pos-1];
				
				for(char c : columnChars)
				{
					if(validChars.contains(c) && refGenome.get(entry.getKey()).charAt(pos-1)!=c)
						toChars.add(c);
				}
				
				for(char c : toChars)
				{
					if(!first)
						bw.newLine();
					else
						first=false;
					
					bw.append(entry.getKey()+"\t"+pos+"\t"+refGenome.get(entry.getKey()).charAt(pos-1)+"\t"+c);
				}
			}
		
		bw.close();
		
		
		//Write SNP table with SnpEffInfos
		if((new File(snpEffOutputFile)).exists())
		{
			System.out.println("Writing SNP table:\n"+outSNPtableWithSnpEffInfos);
			
			
			//SNPeff SNPs
			List<SNPeffSNP> esnps = Read.readSNPeffSNPs(snpEffOutputFile);
			
			Map<String,Map<Integer,List<SNPeffSNP>>> esnpsmap = new LinkedHashMap<String,Map<Integer, List<SNPeffSNP>>>();
			
			for(SNPeffSNP esnp : esnps)
			{
				if(!refGenome.containsKey(esnp.chromName))
					throw new Error("Chromosome/contig ID "+esnp.chromName+" not part of reference. ID appears in SNPeff file: "+snpEffOutputFile);
				if(!esnpsmap.containsKey(esnp.chromName))
				{
					esnpsmap.put(esnp.chromName, new LinkedHashMap<Integer,List<SNPeffSNP>>());
				}
				if(!esnpsmap.get(esnp.chromName).containsKey(esnp.getPos()))
				{
					esnpsmap.get(esnp.chromName).put(esnp.getPos(), new LinkedList<SNPeffSNP>());
				}
				
				esnpsmap.get(esnp.chromName).get(esnp.getPos()).add(esnp);
			}
			
			//Proteins
			Map<String,Gene> geneMap = new LinkedHashMap<String, Gene>();
			
			for(Gene g : Read.parseGFF(refGFF))
				geneMap.put(g.name, g);
			
			//Write
			
			snptabbw = new BufferedWriter(new FileWriter(outSNPtableWithSnpEffInfos));
			
			snptabbw.write("Chrom\tPosition\tRef\tSNP");
			for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
			{
				snptabbw.write("\t"+getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]));
			}
			snptabbw.write("\tSNP Effect\tGene ID\tGene name\tGene function\told_AA/new_AA\tOld_codon/New_codon\tCodon_Num(CDS)\tCDS_size");
			snptabbw.newLine();
			
			//char tmpchar;
			Gene g;
			String anno;
			String length;
			for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
				for(int pos : entry.getValue())
				{
					for(SNPeffSNP es : esnpsmap.get(entry.getKey()).get(pos))
					{
						g = geneMap.get(es.geneID);
						
						//anno/length
						if(g!=null)
						{
							anno = g.anno;
							length = Integer.toString(g.length());
						}
						else
						{
							anno = "";
							length = "";
						}
						
						
						
						snptabbw.write(entry.getKey()+"\t"+pos+"\t"+refGenome.get(entry.getKey()).charAt(pos-1)+"\t"+es.to);
						
						for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
						{
							snptabbw.write("\t");
							tmpchar = snpColumns.get(entry.getKey())[pos-1][vcfIndex];
							if(tmpchar==refGenome.get(entry.getKey()).charAt(pos-1))
								snptabbw.write(".");
							else
							{
								snptabbw.write(tmpchar);
								
								if(writeFreqsInStatTable && tmpchar!='N')
								{
									snptabbw.write(" ("+Math.round(snpFrequencies.get(entry.getKey())[pos-1][vcfIndex]*1000d)/10d+")");
								}
							}
						}
						
						snptabbw.write("\t"+es.effect+"\t"+es.geneID+"\t"+es.geneName+"\t"+anno+"\t"+es.aaChange+"\t"+es.codonChange+"\t"+es.codonNum+"\t"+length);
						
						snptabbw.newLine();
					}
				}
			
			snptabbw.close();
		}
		
		//Write SNP table with SnpEffInfos with uncertainty calls
		//Identical to previous code (3 differences)
		if((new File(snpEffOutputFile)).exists())
		{
			System.out.println("Writing SNP table:\n"+outSNPtableWithUncertaintyCallsWithSnpEffInfos); // 1/3 differences
			
			
			//SNPeff SNPs
			List<SNPeffSNP> esnps = Read.readSNPeffSNPs(snpEffOutputFile);
			
			Map<String,Map<Integer,List<SNPeffSNP>>> esnpsmap = new LinkedHashMap<String,Map<Integer, List<SNPeffSNP>>>();
			
			for(SNPeffSNP esnp : esnps)
			{
				if(!refGenome.containsKey(esnp.chromName))
					throw new Error("Chromosome/contig ID "+esnp.chromName+" not part of reference. ID appears in SNPeff file: "+snpEffOutputFile);
				if(!esnpsmap.containsKey(esnp.chromName))
				{
					esnpsmap.put(esnp.chromName, new LinkedHashMap<Integer,List<SNPeffSNP>>());
				}
				if(!esnpsmap.get(esnp.chromName).containsKey(esnp.getPos()))
				{
					esnpsmap.get(esnp.chromName).put(esnp.getPos(), new LinkedList<SNPeffSNP>());
				}
				
				esnpsmap.get(esnp.chromName).get(esnp.getPos()).add(esnp);
			}
			
			//Proteins
			Map<String,Gene> geneMap = new LinkedHashMap<String, Gene>();
			
			for(Gene g : Read.parseGFF(refGFF))
				geneMap.put(g.name, g);
			
			//Write
			
			snptabbw = new BufferedWriter(new FileWriter(outSNPtableWithUncertaintyCallsWithSnpEffInfos)); // 2/3 differences
			
			snptabbw.write("Chrom\tPosition\tRef\tSNP");
			for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
			{
				snptabbw.write("\t"+getSampleNameFromPath(args[vcfIndex+vcfArgumentsOffset]));
			}
			snptabbw.write("\tSNP Effect\tGene ID\tGene name\tGene function\told_AA/new_AA\tOld_codon/New_codon\tCodon_Num(CDS)\tCDS_size");
			snptabbw.newLine();
			
			//char tmpchar;
			Gene g;
			String anno;
			String length;
			for(Map.Entry<String, List<Integer>> entry : snpPositionList.entrySet())
				for(int pos : entry.getValue())
				{
					for(SNPeffSNP es : esnpsmap.get(entry.getKey()).get(pos))
					{
						g = geneMap.get(es.geneID);
						
						//anno/length
						if(g!=null)
						{
							anno = g.anno;
							length = Integer.toString(g.length());
						}
						else
						{
							anno = "";
							length = "";
						}
						
						
						
						snptabbw.write(entry.getKey()+"\t"+pos+"\t"+refGenome.get(entry.getKey()).charAt(pos-1)+"\t"+es.to);
						
						for(int vcfIndex=0; vcfIndex<numVCFs; vcfIndex++)
						{
							snptabbw.write("\t");
							tmpchar = uncertainSnpColumns.get(entry.getKey())[pos-1][vcfIndex]; // 3/3 differences
							if(tmpchar==refGenome.get(entry.getKey()).charAt(pos-1))
								snptabbw.write(".");
							else
							{
								snptabbw.write(tmpchar);
								
								if(writeFreqsInStatTable && tmpchar!='N')
								{
									snptabbw.write(" ("+Math.round(snpFrequencies.get(entry.getKey())[pos-1][vcfIndex]*1000d)/10d+")");
								}
							}
						}
						
						snptabbw.write("\t"+es.effect+"\t"+es.geneID+"\t"+es.geneName+"\t"+anno+"\t"+es.aaChange+"\t"+es.codonChange+"\t"+es.codonNum+"\t"+length);
						
						snptabbw.newLine();
					}
				}
			
			snptabbw.close();
		}
		
		date = new Date();
		infobw.write("Run finished: "+date.toGMTString()+"\n");
		
		infobw.write("\nList of VCF files:\n");
		for(int vcfIndex =0; vcfIndex<numVCFs; vcfIndex++)
		{
			infobw.write(args[vcfIndex+vcfArgumentsOffset]+"\n");
		}
		
		infobw.close();
		
		//Messages about outgroup
		if(numOutgroups==0)
			System.out.println("No outgroup has been defined. All samples will be treated equally.");
		if(numOutgroups==1)
			System.out.println("One sample has been labeled as outgroup.\nSNPs only called in this sample were not considered in the SNP alignment or SNP tables.\nBut they were counted in the statistics table.");
		if(numOutgroups>1)
			System.out.println("WARNING: Multiple samples have been labeled as outgroup!\nSNPs only called in these samples were not considered in the SNP alignment or SNP tables.\nBut they were counted in the statistics table.");
		System.out.println("");
		
		System.out.println("All done! ("+Math.round((System.currentTimeMillis()-startTime)/60000d)+" minutes)");
	}
	
	private static void excludePositionsFromSet(Map<String,Set<Integer>> positions, String posToExcludeFiles) throws Exception
	{
		String[] filenames = posToExcludeFiles.split(",");
		
		File excludefile = new File(filenames[0]);
		
		System.out.println("Excluding positions...");
		
		int count =0;
		BufferedReader br;
		
		//exclude regions (like rep regions, certain genes, etc)
		if(excludefile.exists())
		{
			
			String[] cells;
			String chromName;
			int start;
			int end;
			
			br = new BufferedReader(new FileReader(excludefile));
			for(String line=br.readLine(); line!=null;line=br.readLine())
			{
				line = line.trim();
				if(line.length()==0)
					continue;
				if(line.startsWith("#"))
					continue;
				
				cells = line.split("[\\t]");
				
				chromName = cells[0];
				
				// start = 3
				start = Integer.parseInt(cells[3]);
				
				// end = 4
				end = Integer.parseInt(cells[4]);
				
				Set<Integer> set = positions.get(chromName);
				
				if (set == null)
				{
				    throw new Error("Chromosome/contig ID "+chromName+" not part of reference. ID appears in file: "+posToExcludeFiles);
				}
				
				for(int i=start;i<=end;i++)
				{
					if(set.contains(i))
					{
						count++;
						set.remove(i);
					}
				}
			}
			
			br.close();
		
		}

		//exclude 1st and 2nd codon position
		if(filenames.length>1)
		{
			excludefile = new File(filenames[1]);
			
			if(excludefile.exists())
			{
				List<Gene> cdss = Read.getCDSfromGFF(excludefile.getAbsolutePath());
				
				for(Gene g : cdss)
				{
					Set<Integer> set = positions.get(g.chromName);
					
					if (set == null)
					{
					    throw new Error("Chromosome/contig ID "+g.chromName+" not part of reference. ID appears in file: "+posToExcludeFiles);
					}
					
					if(g.strand=='+')
					{
						for(int posGenome=g.start, posGene=1; posGenome<=g.end; posGenome++,posGene++)
						{
							if(posGene%3!=0)
							{
								count++;
								set.remove(posGenome);
							}
						}
					}
					else if(g.strand=='-')
					{
						for(int posGenome=g.end, posGene=1; posGenome>=g.start; posGenome--,posGene++)
						{
							if(posGene%3!=0)
								set.remove(posGenome);
						}
					}
				}
			}
		}
		
		
		
		System.out.println(count+" SNP positions excluded.");
	}
	
	private static Map<String,Set<Integer>> getPositionsToExclude(String posToExcludeFile) throws Exception
	{
		File infile = new File(posToExcludeFile);
		
		Map<String,Set<Integer>> res = new LinkedHashMap<String,Set<Integer>>();
		
		if(!infile.exists())
		{
			System.err.println("No positions to exclude provided! All positions will be used!");
			return res;
		}
		
		
		
		String[] cells;
		String chromName;
		int start;
		int end;
		
		BufferedReader br = new BufferedReader(new FileReader(infile));
		for(String line=br.readLine(); line!=null;line=br.readLine())
		{
			line = line.trim();
			if(line.length()==0)
				continue;
			if(line.startsWith("#"))
				continue;
			
			cells = line.split("[\\t]");
			
			chromName = cells[0];
			
			// start = 3
			start = Integer.parseInt(cells[3]);
			
			// end = 4
			end = Integer.parseInt(cells[4]);
			
			Set<Integer> set = res.get(chromName);
			
			if (set == null)
			{
			    set = new HashSet<>();
			    res.put(chromName, set);
			}
			
			for(int i=start;i<=end;i++)
			{
				set.add(i);
			}
		}

		br.close();
		
		return res;
	}
	
	public static boolean parseBoolean(String boo)
	{
		boolean res = false;
		if(boo.equalsIgnoreCase("true") || boo.equalsIgnoreCase("T") || boo.equalsIgnoreCase("1"))
			res=true;
		return res;
	}
	
	public static char getAmbiguousBase(char c1, char c2)
	{
		Set<Character> chars = new HashSet<Character>();
		chars.add(c1);
		chars.add(c2);
		
		if(c1==c2)
			return c1;
		
		if(chars.contains('G') && chars.contains('A'))
			return 'R';
		if(chars.contains('T') && chars.contains('C'))
			return 'Y';
		if(chars.contains('G') && chars.contains('T'))
			return 'K';
		if(chars.contains('A') && chars.contains('C'))
			return 'M';
		if(chars.contains('G') && chars.contains('C'))
			return 'S';
		if(chars.contains('A') && chars.contains('T'))
			return 'W';
		
		System.err.println("Illegal arguments in function getAmbiguousBase: "+c1+", "+c2);
		
		return 'N';
	}
	
	public static String getSampleNameFromPath(String sampleNameWithPath)
	{
		String[] res = sampleNameWithPath.split("/");
		
		if(res.length>=1)
			return res[res.length-1];
		else
			return sampleNameWithPath;
	}
	
	public static int getGenotypeEncoding(char nucleotide)
	{
		int res = -9;
		
		switch (nucleotide)
		{
			case 'A': res = 1;
			break;
			
			case 'C': res = 2;
			break;
			
			case 'G': res = 3;
			break;
			
			case 'T': res = 4;
			break;
			
			case 'N': res = -9;
			break;
			
			default: res = -9;
			System.err.println("Warning: No genotype encoding for invalid character '"+nucleotide+"'!\nEncoding is set to '-9' to indicate missing data.");
		
		}
		
		return res;
	}
	
	public static boolean hasMissingData(char[] snpCol, char nChar)
	{
		boolean res = false;
		
		for(char snp : snpCol)
			if(snp == nChar)
				res = true;
		
		return res;
	}

}
